# Generated by Django 5.2 on 2025-04-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotqa',
            name='answer',
            field=models.TextField(help_text='Answer(English)'),
        ),
        migrations.AlterField(
            model_name='chatbotqa',
            name='question',
            field=models.CharField(help_text='Question Keywords(English)', max_length=255, unique=True),
        ),
    ]
