# Generated by Django 5.2 on 2025-04-13 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='aqi_max',
            field=models.FloatField(default=100.0, help_text='AQI上限'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='co2_max',
            field=models.FloatField(default=1000.0, help_text='CO2浓度上限 (ppm)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='humidity_max',
            field=models.FloatField(default=80.0, help_text='湿度上限 (%)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='humidity_min',
            field=models.FloatField(default=20.0, help_text='湿度下限 (%)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pm10_max',
            field=models.FloatField(default=150.0, help_text='PM10浓度上限 (μg/m³)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pm25_max',
            field=models.FloatField(default=35.0, help_text='PM2.5浓度上限 (μg/m³)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='temp_max',
            field=models.FloatField(default=30.0, help_text='温度上限 (°C)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='temp_min',
            field=models.FloatField(default=10.0, help_text='温度下限 (°C)'),
        ),
    ]
