# Generated by Django 5.2 on 2025-04-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_aqi_max_userprofile_co2_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='aqi_max',
            field=models.FloatField(default=100.0, help_text='Maximum AQI'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='co2_max',
            field=models.FloatField(default=1000.0, help_text='Maximum CO2 level (ppm)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email_notifications',
            field=models.BooleanField(default=False, help_text='Receive email alerts for sensor data alerts'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='humidity_max',
            field=models.FloatField(default=80.0, help_text='Maximum humidity (%)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='humidity_min',
            field=models.FloatField(default=20.0, help_text='Minimum humidity (%)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pm10_max',
            field=models.FloatField(default=150.0, help_text='Maximum PM10 level (μg/m³)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pm25_max',
            field=models.FloatField(default=35.0, help_text='Maximum PM2.5 level (μg/m³)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='temp_max',
            field=models.FloatField(default=30.0, help_text='Maximum temperature (°C)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='temp_min',
            field=models.FloatField(default=10.0, help_text='Minimum temperature (°C)'),
        ),
    ]
