# Generated by Django 5.1.2 on 2025-04-24 05:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0004_alter_userprofile_aqi_max_alter_userprofile_co2_max_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="api_key",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, help_text="API Key for the user"
            ),
        ),
    ]
