# Generated by Django 5.1.2 on 2025-04-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_userprofile_api_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="api_key",
            field=models.CharField(
                blank=True,
                help_text="Optional: Your personal API Key for the external LLM service.",
                max_length=255,
                null=True,
            ),
        ),
    ]
